//---------------------------------------------------------------------------
#include <vcl\condefs.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ffttest.cpp"

#pragma hdrstop
//---------------------------------------------------------------------------
USERES("fft2.res");
USEUNIT("\Program Files\Borland\CBuilder\Projects\I FFT2\ifttest.cpp");
//---------------------------------------------------------------------------
int main(int argc, char **argv)
{
    fmain();
	return 0;

}
//---------------------------------------------------------------------------
