[InstallSHIELD Silent]
Version=v3.00.00
File=Response File

[DlgOrder]
Dlg0=SdRegisterUser-0
Dlg1=SdAskDestPath-0
Dlg2=SdSelectFolder-0
Dlg3=SdStartCopy-0
Dlg4=SdFinish-0
Count=5

[SdRegisterUser-0]
Result=1
szName=Name
szCompany=Your Company

[SdAskDestPath-0]
Result=1
szDir=<ProgramFilesDir>\NMR Imaging

[SdSelectFolder-0]
Result=1
szFolder=NMR Imaging

[SdStartCopy-0]
Result=1

[SdFinish-0]
Result=0
bOpt1=0
bOpt2=0
